### PR TITLE
SDK code samples cleanups - initial

### PR DESCRIPTION
**Pull request by karollewandowski**
Initial cleanups of invalid and obsolete configurations.

I also changed Gradle projects names for cleaner Project view tree:
Screenshot 2022-04-29 at 15 21 50

### CODE REVIEW

**Comment by YannCebron** [comment]
https://plugins.jetbrains.com/docs/intellij/sdk-code-guidelines.html#directory-naming-conventions-for-sdk-plugins (not saying we _must_ keep this systematic)

**Comment by YannCebron** [comment]
paths in `.github/workflows/code-samples.yml` and `.github/dependabot.yml` must be adapted

**Review by YannCebron — CHANGES_REQUESTED** [review]
see above

**Comment by hsz** [comment]
@YannCebron As directories names didn't change, there's no need for adjusting GitHub Actions or Dependabot.

**Pull request merged**
