### PR TITLE
Added Nette framework plugins to PhpStorm existing plugins

### PR DESCRIPTION
**Pull request by mesour**

### CODE REVIEW

**Comment by YannCebron** [comment]
Thanks a lot for your patch. Would you mind formatting the content in a more dense structure, e.g. a table? Let me know if that will work for you.

**Comment by mesour** [comment]
Yes, I can reformat it for example to a table. Do you have any example (some other page in documentation) of how you would imagine it?

**Comment by YannCebron** [comment]
Maybe a table with these columns

|Name|Description|Website|GH|Plugin|

last 3 (links) could have very short text to save width (`[X](someLink)`)

**Comment by mesour** [comment]
I updated it. Is it OK now?

**Comment by YannCebron** [comment]
Thanks a lot, perfect 👍

**Pull request merged**
