### PR TITLE
Migrate to sdkdocs_template

### PR DESCRIPTION
**Pull request by citizenmatt**
Migrates away from the private `webhelp-template` submodule to use the open [JetBrains/sdkdocs-template](https://github.com/JetBrains/sdkdocs-template) repo instead. This repo is already being used by [JetBrains/resharper-devguide](https://github.com/JetBrains/resharper-devguide), and moves (nearly) all of the scripts out of this repo, and into the `sdkdocs-template` repo.

**NOT READY FOR MERGING. STILL TO DO:**

- [x] Remove `webhelp-template` submodule
- [x] Add `sdkdocs-template` submodule
- [x] Remove unnecessary scripts in `intellij-sdk-docs` repo + fixup config
- [x] Fixup existing `.md` files (remove unused layout)
- [ ] Edit on GitHub link is currently missing
- [x] Update CONTRIBUTING.md with instructions for getting it up and running
- [x] Document running on Windows (it does work!)
- [x] Document features
- [x] Link checker jekyll plugin

## New features
* _SUMMARY.md can have sections + placeholders. Sections are defined with h2 (`##`) headings and a new bullet list. Placeholders allow for empty nodes in the tree, that are rendered greyed out. Very useful for seeing the structure that we're aiming for, and what's missing. See [resharper-devguide](https://www.jetbrains.com/resharper/devguide/) for an example
* Redirects. Includes the [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) plugin, to allow for redirecting from a previous location when renaming/moving files. Also useful for redirecting from e.g. index.html &rarr; README.md
* Each page shows "Last Updated" date from last git check in (this does slow down the build, so might look at only doing this for production builds)
* Callouts by using markdown block quotes, e.g. `> **NOTE** Blah blah` will create a "note" callout. Supported types are `NOTE`, `WARNING`, `TIP` and `TODO`.
* Automatic table of contents in a page, based on headings. Define with:

    ```
    * Placeholder bullet list, gets replaced
    {:toc}
    ```

Check out the [README](https://github.com/JetBrains/sdkdocs-template#readme) for sdkdocs-template for more details (although that probably needs updating with details for running on Windows).

## Lost features
* Link checking. Needs to be added back in, probably as separate PR
* Edit on GitHub link. Needs to be added back ASAP

### CODE REVIEW

**Comment by breandan** [comment]
I was able to follow the steps on Windows 8.1 (x64) up to Step 5 under [Bootstrapping the environment](https://github.com/citizenmatt/intellij-sdk-docs/blob/sdkdocs-template/CONTRIBUTING.md#bootstrapping-the-environment), which failed with [this error](https://gist.github.com/breandan/29ac60da1dcc8c82b981). The [Nokogiri documentation](http://www.nokogiri.org/tutorials/installing_nokogiri.html#windows) seems to indicate that Rubygems 2.4.5 or later is required in order to build it, but native gem installation is broken on Windows [past 2.4.0](https://github.com/rubygems/rubygems/issues/977). Uncertain how to proceed.

**Comment by citizenmatt** [comment]
Sigh. The `link-checker` gem relies on an older version of `nokogiri` that doesn't compile on Windows. The newer version does, but `link-checker` won't load it. I think I'll need a custom build of `link-checker` that uses newer dependencies.

**Comment by citizenmatt** [comment]
Right, it should all work on Windows now. I've fixed all of the broken local links, including images. But there are still failing links to external sites (e.g. github, devnet, etc.) These still need fixing, and can be found by running `rake links`.

There's a small issue in that the `Gemfile.lock` file is different on Mac and Windows, so it appears changed after pulling and running `rake bootstrap`. I'm trying to find a fix, but it could be removing `Gemfile.lock`.

**Comment by breandan** [comment]
Great, all sorted now. Thanks @citizenmatt!

**Pull request merged**
