### PR TITLE
Update api_changes_list_2024.md

### PR DESCRIPTION
**Pull request by dmitry-avdeev**
package removed

### CODE REVIEW

**Comment by YannCebron** [comment]
This is not a valid pattern. What classes are affected here in addition to the one already listed?

**Comment by dmitry-avdeev** [comment]
I've just moved a class, changing its package. "class moved" is already documented, the whole change would be

### Markdown Plugin 2024.1
`org.intellij.plugins.markdown.ui.split` package removed
`org.intellij.plugins.markdown.ui.split.SplitTextEditorProvider` class removed
: `com.intellij.openapi.fileEditor.TextEditorWithPreviewProvider` should be used instead

**Comment by dmitry-avdeev** [comment]
Without "package removed" I still get

Package 'org.intellij.plugins.markdown.ui.split' is not found

**Comment by YannCebron** [comment]
I see. I'll add correct entry and mute test.

**Pull request closed without merging**
