### PR TITLE
fix include wrong file and icon dead link issue

### PR DESCRIPTION
**Pull request by zjhmale**
* should include `SimpleLanguage.java` instead of `Simple.bnf` in the `Define the language` section.
* fix dead link for the icon.

@YannCebron

### CODE REVIEW

**Comment by yole** [comment]
Why do you think the include file link is wrong? It's correct.

**Comment by zjhmale** [comment]
@yole cause `SimpleFIleType.java` `SimpleTokenType.java` and `SimpleElementType.java` all dependent on `SimpleLanguage.java` and `Simple.bnf` just appearances in the `Grammar and Parser` chapter.

`SimpleLanguage.java` is the foundation element of this tutorial, and the section title is `Define the language` but not `Define the Parser and PSI for the language`.

**Comment by zjhmale** [comment]
poke @yole

**Comment by breandan** [comment]
@zjhmale You're right. [This mistake](https://github.com/JetBrains/intellij-sdk-docs/commit/b940673f47a3f102324f79e53cadc4fc111d083c#diff-a69807dcce170a2adf573d85726ef106) was introduced when we migrated from embedded code snippets to Liquid tags. Thanks for the PR!

**Comment by zjhmale** [comment]
you're welcome :)

**Pull request merged**
