### PR TITLE
Update working_with_text.md

### PR DESCRIPTION
**Pull request by Phate334**

### CODE REVIEW

**Comment by YannCebron** [comment]
Thanks for spotting

**Comment by calexHG** [comment]
You know, arguably: the original version could have just been viewed as being lazy about indentation _[and of rather naturally assuming you might have more actions other than the example, so not closing the `actions` tag within the limited excerpt of the plugin descriptor it quoted.]_ 

This fix, however, is buggy no matter how ya look at it. Hehe ;p

(patch coming up; then you'll know what I mean :blush:)

**Comment by calexHG** [comment]
Patch for the minor typo introduced by this PR:
https://github.com/JetBrains/intellij-sdk-docs/pull/56

**Comment by Phate334** [comment]
My bad! 
I miss that `</action>` tag in next line.

**Comment by calexHG** [comment]
@Phate334 Hehe. No problem, of course! :blush: 
I might not ever have bothered with requesting the original tiny fix, but since we _were_  bothering to upgrade that excerpt, I couldn't help but make sure the upgraded excerpt was correct :sunglasses:

It's just a compulsion of mine ;)
Thanks for the contrib. Cheers.

**Pull request merged**
