### PR TITLE
`com.jetbrains.php.docTagParserExtension` EP marked as internal in `php_extension_point_list.md`

### PR DESCRIPTION
**Pull request by i582**

### CODE REVIEW

**Comment by YannCebron** [comment]
Thanks, that's actually a discrepancy between the EP declaration `PhpDocTagParserEP` having internal status vs. EP implementation `PhpDocTagParser` status (non-internal)

**Comment by i582** [comment]
Yep, that looks weird too.

**Comment by YannCebron** [comment]
@wbars please review, do not apply patch. we generate these lists from actual sources. thanks

**Comment by YannCebron** [comment]
ApiStatus was updated in sources, changes will be in effect once EP page is regenerated from corresponding branch on release

**Pull request closed without merging**
